### ISSUE TITLE
[Feature Request] Remember "order by" dropdown menu choice

### ISSUE THREAD

**Issue by thierry400** [curtwagner1984/YAPO#11]
It would be nice if YAPO remembers how you  usually order your scene's, actors, websites, ..

**Comment by curtwagner1984** [comment]
You mean like setting a default option for sort order for everything, and that so it will be persistent even after turning the server on and off? If that's what you mean we can store it in the settings file I would imagine.

**Comment by thierry400** [comment]
Yes that is exactly what I mean.

(And sorry for the late response, havn't had alot of spare time the last few days)

**Comment by curtwagner1984** [comment]
Ok, so I made it so 'order by' will persist. Also I added 'random' and 'date added' sort options for folders. This will require to call `makemigrations` and then `migrate` when upgrading.

**Comment by thierry400** [comment]
Thanks! it indeed is working perfectly!

I did however get the following error while doing 'makemigrations:

(py3virtualenv) C:\Yapo\YAPO>python makemigrations
python: can't open file 'makemigrations': [Errno 2] No such file or directory

(py3virtualenv) C:\Yapo\YAPO>python manage.py makemigrations
Static files dir is: C:\Yapo\YAPO\videos\static
Media files dir is: C:\Yapo\YAPO\videos\media
C:\Program Files (x86)\VideoLAN\VLC\vlc.exe
Last full scene tagging : 2016-08-23 22:17:36
System check identified some issues:

WARNINGS:
videos.Actor.actor_aliases: (fields.W340) null has no effect on ManyToManyField.
videos.Actor.actor_tags: (fields.W340) null has no effect on ManyToManyField.
videos.Folder.scenes: (fields.W340) null has no effect on ManyToManyField.
videos.Scene.actors: (fields.W340) null has no effect on ManyToManyField.
videos.Scene.scene_tags: (fields.W340) null has no effect on ManyToManyField.
videos.Scene.websites: (fields.W340) null has no effect on ManyToManyField.
videos.Website.scene_tags: (fields.W340) null has no effect on ManyToManyField.
You are trying to add a non-nullable field 'date_added' to folder without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows)
 2) Quit, and let me add a default in models.py
Select an option:


I fixed it like i fixed it like you told me last time, by choosing option 1 and typing ' datetime.datetime.now() '

**Comment by curtwagner1984** [comment]
@thierry400 Yes, this is what you were supposed to do. I think this should be added to the update instructions on the main page.

**Comment by firewalkwithme93** [comment]
I'm trying to solve the date_added error, I'm selecting the first option and putting in 'datetime.datetime.now()' but it just asks me again. Am I getting the wrong end of the stick on this?

**Comment by sjclayton** [comment]
@firewalkwithme93 Because the modified_date field was added to a shit load of the models for the database, you need to do it a bunch of times... just keep doing it over and over until it goes... like, it takes maybe 7 times or so...  =D

**Comment by firewalkwithme93** [comment]
Ah! Thanks! :D

**Comment by curtwagner1984** [comment]
Ok, I think we can consider this issue closed.
