### ISSUE TITLE
removing tags out tag list doesn't seem to work

### ISSUE THREAD

**Issue by thierry400** [curtwagner1984/YAPO#12]

**Comment by sjclayton** [comment]
I can confirm it doesn't work in the Actor tag list... not sure about the Scene tag list, as I haven't added any yet because I'm still mainly doing testing more so than actually using YAPO for my collection

**Comment by curtwagner1984** [comment]
Yeah, this doesn't work because I haven't implemented this functionality yet. I will do so ASAP.

**Comment by curtwagner1984** [comment]
This should work now. There are two icons. The x icon will show up when it's not a main page IE actor-tags that are part of an actor page, then clicking on the x will only remove the tag from the current actor. The garbage icon will show up if it's a main page IE under actor-tag in the main menu then clicking it will remove the tag from the database.

This works with actor\scene tags and websites.

**Comment by curtwagner1984** [comment]
Anyone can confirm it's working correctly?

**Comment by curtwagner1984** [comment]
Since no one complained it doesn't work, I'll assume that it does.

**Comment by sjclayton** [comment]
I tested it with scene tags and it worked fine... I'm not sure about actor tags though, but assume it'll work just the same.
