### ISSUE TITLE
[Bug] Generate Sample Video not working on Linux

### ISSUE THREAD

**Issue by sjclayton** [curtwagner1984/YAPO#13]
I tried the modification you posted in the forum on Emp adding single quotes to that line in ffmpeg_process.py worked for me, and it generated the sample video... I didn't really want to change it here however and make a new commit after having fixed it as I don't quite remember how Windows handles single quotes on the command line.

Here is the corrected line:

    scale_argument = "-vf scale={},'pad=ih*16/9:ih:(ow-iw)/2:(oh-ih)/2'".format(SAMPLE_RESOLUTION)

The only issue now is that after generating the sample video the code that is supposed to remove the temp image files isn't working. But I think I may be able to fix it.

**Comment by sjclayton** [comment]
I fixed the issue with the temp files not being removed after the sample video is generated -- pushed in my latest pull request, and I'm also going to submit the adjustment made the the line I mentioned above... let me know if it breaks anything on Windows @curtwagner1984

**Comment by curtwagner1984** [comment]
It does indeed break the sample generation on windows: 
`No such filter: 'pad=ih*16/9:ih:(ow-iw)/2:(oh-ih)/2'\r\nError opening filters!\r\n"`

It's strange... Does it work on linux with generating screenshots for the scenes on import? It uses the same padding argument:
`FFMPEG_SCREENSHOT_ARGUMENTS = "-vf \"thumbnail,scale=1280:720,pad=ih*16/9:ih:(ow-iw)/2:(oh-ih)/2\" -frames:v 1"`

As the scale argument: 
`scale_argument = "-vf scale={},'pad=ih*16/9:ih:(ow-iw)/2:(oh-ih)/2'".format(SAMPLE_RESOLUTION)`

**Comment by sjclayton** [comment]
I have not checked to see if it works on import or not.... I will do so... but I know that it didn't work generating them afterwards without adding those single quotes to the scale_argument line.

Something has to be able to be figured out to get it to work, or else OS specific code will need to be added, so that it runs with the correct quoting (single on Linux and no quotes on Windows)...

**Comment by sjclayton** [comment]
Fixed it!!! =D Newest pull request will have the fixed code that should work on both OSes.... 

The arguments being passed to ffmpeg needed to be treated escaped or treated as a regex... like in the line:

FFMPEG_SCREENSHOT_ARGUMENTS = "-vf \"thumbnail,scale=1280:720,pad=ih*16/9:ih:(ow-iw)/2:(oh-ih)/2\" -frames:v 1"

**Comment by curtwagner1984** [comment]
Tested and it works on windows as well! Cheers!

**Comment by sjclayton** [comment]
@curtwagner1984 I opened a new issue for the other bug. You can close this now!
