### ISSUE TITLE
[Bug] Screenshots / Sample Videos not being removed from disk after removing scene from the database.

### ISSUE THREAD

**Issue by sjclayton** [curtwagner1984/YAPO#18]
Upon removing (deleting) a scene from the database, the screenshots / sample videos generated for said scene that are stored in /media/scenes/{Scene ID}/ are not being deleted from disk.

**Comment by curtwagner1984** [comment]
Added this functionality to the 'clean database' option in settings. Now it should remove actor\scene folders from the /media/ folder if they are no longer in the database.

**Comment by sjclayton** [comment]
@curtwagner1984 Alrighty -- I'll test it and let you know if there is any issues.

**Comment by sjclayton** [comment]
@curtwagner1984 It appears to work just fine!! =D

Quick side question: You have it checking for Actors no longer in the database, but as of yet there is no way of actually deleting an Actor.

**Comment by curtwagner1984** [comment]
@sjclayton There is, on the main actor page there should be garbage icons near the actors instead the usual x this should delete actors from the db.

**Comment by sjclayton** [comment]
@curtwagner1984 Thanks! Apparently I'm fucking blind =P
