### ISSUE TITLE
[Bug] Cannot import .MKV video files

### ISSUE THREAD

**Issue by sjclayton** [curtwagner1984/YAPO#22]
It appears that YAPO is unable to import MKV video files... I just noticed this when importing a folder, as all other files were added to the database except the one MKV in the folder.

**Comment by curtwagner1984** [comment]
Added MKV to accepted extensions:
ACCEPTED_VIDEO_EXTENSIONS = {".mp4", ".avi", ".mov", ".flv", ".rm", ".wmv", ".mov", ".m4v", ".mpg", ".mpeg", ".mkv"}

**Comment by sjclayton** [comment]
@curtwagner1984 did you add this, but not commit it then?

**Comment by curtwagner1984** [comment]
Perhaps, try now.

**Comment by sjclayton** [comment]
We're all good now! I noticed that line when poking around, and had modified it locally just before you mentioned it... but didn't get a chance to push the change =P
