### ISSUE TITLE
[Feature Request] Add button to play random scene

### ISSUE THREAD

**Issue by sjclayton** [curtwagner1984/YAPO#27]
Add a button to play a random scene, chosen from either all scenes in the database when in Scene view or from scenes by a specific actor when in Actor detail view.

**Comment by firewalkwithme93** [comment]
Excellent suggestion, finding random scenes is possible with the filter but this makes things even more simple :)

**Comment by sjclayton** [comment]
Yes I'm aware you can sort that way with the filter.... I believe this feature would basically negate the need to Order by Random as, in essence doing that is kind of pointless. I don't want to just see a big list of 100's of scenes randomized and still have to scroll through and pick one, I'd rather just click a button and be surprised =P

**Comment by curtwagner1984** [comment]
Partially implemented ''[Feature Request] Add button to play random scene #27'. Play random scene works with scene, actors, websites and scenetags but only when the search term is blank.

**Comment by curtwagner1984** [comment]
@sjclayton I think the point of a random ordering is for sort of discovering items you forgot you had. 
When your collection is big enough, you are not aware of most of it, so having scenes pop up in an random order will allow you to discover scenes you didn't know you had.

**Comment by sjclayton** [comment]
@curtwagner1984 Yeah I get that, sorry my comment wasn't meant to mean that there is reason to remove that function.

**Comment by firewalkwithme93** [comment]
Great feature! Thanks very much

**Comment by curtwagner1984** [comment]
It doesn't work with filtered results yet. (When the search box is not empty)
