### ISSUE TITLE
'Order By' selection not retained when switching views

### ISSUE THREAD

**Issue by firewalkwithme93** [curtwagner1984/YAPO#4]
When switching between Grid View and regular view, whatever filter has been selected under 'Order By' is lost. Having this filter remain selected when switching views would be a great Quality Of Life feature.

**Comment by curtwagner1984** [comment]
I changed the way grid view works. Now it should not query the server for a new set of items, instead it will change the view of the items already fetched from the server. This means that the query parameters (search, order etc) should persist over a change of view. In addition in actor detail when switching to grid view now automatically hides actor sidebar.

**Comment by firewalkwithme93** [comment]
Works great from what I can tell!
