### ISSUE TITLE
[Feature Request] Add usage counts to website, scene tag and actor tag lists

### ISSUE THREAD

**Issue by sjclayton** [curtwagner1984/YAPO#42]
Should be usage counts beside the items in each list. Counts should be visible without clicking on a specific tag or website, etc...

**Comment by curtwagner1984** [comment]
@sjclayton [Issue #42] Added 'usage_count' to actor\scene tags, website, actors. Also added option to sort by usage count.

It would also be nice to be able to search by usage_count but the search function had seen better days... Maybe when I'll clean it up I'll add this option.

Also, the usage count is a derived field and not stored in the database so it will take longer to sort by it. It is not noticeable on tags\sites but on actors it takes a few seconds if your collection is large enough.
