### ISSUE TITLE
Can't add anything after installation

### ISSUE THREAD

**Issue by chengbert** [curtwagner1984/YAPO#53]
I hope this is the right place to post this.
I installed YAPO and everything went fine, but now when I start the server I can't add anything.
This is the error I get when navigating to the settings page:
`Something went wrong!{"data":"\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\n  <meta name=\"robots\" content=\"NONE,NOARCHIVE\">\n  <title>OperationalError at /api/folder-local/</title>\n  <style type=\"text/css\">\n    html * { padding:0; margin:0; }\n    body * { padding:10px 20px; }\n    body * * { padding:0; }\n    body { font:small sans-serif; }\n    body>div { border-bottom:1px solid #ddd; }\n    h1 { font-weight:normal; }\n    h2 { margin-bottom:.8em; }\n    h2 span { font-size:80%; color:#666; font-weight:normal; }\n    h3 { margin:1em 0 .5em 0; }\n    h4 { margin:0 0 .5em 0; font-weight: normal; }\n    code, pre { font-size: 100%; white-space: pre-wrap; }\n    table { border:1px solid #ccc; border-collapse: collapse; width:100%; background:white; }\n    tbody td, tbody th { vertical-align:top; padding:2px 3px; }\n    thead th {\n      padding:1px 6px 1px 3px; background:#fefefe; text-align:left;\n      font-weight:normal; font-size:11px; border:1px solid #ddd;\n    }\n    tbody th { width:12em; text-align:right; color:#666; padding-right:.5em; }\n    table.vars { margin:5px 0 2px 40px; }\n    table.vars td, table.req td { font-family:monospace; }\n    table td.code { width:100%; }\n    table td.code pre { overflow:hidden; }\n    table.source th { color:#666; }\n    table.source td { font-family:monospace; white-space:pre; border-bottom:1px solid #eee; }\n    ul.traceback { list-style-type:none; color: #222; }\n    ul.traceback li.frame { padding-bottom:1em; color:#666; }\n    ul.traceback li.user { background-color:#e0e0e0; color:#000 }\n    div.context { padding:10px 0; overflow:hidden; }\n    div.context ol { padding-left:30px; margin:0 10px; list-style-position: inside; }\n    div.context ol li { font-family:monospace; white-space:pre; color:#777; cursor:pointer; padding-left: 2px; }\n    div.context ol li pre { display:inline; }\n    div.context ol.context-line li { color:#505050; background-color:#dfdfdf; padding: 3px 2px; }\n    div.context ol.context-line li span { position:absolute; right:32px; }\n    .user div.context ol.context-line li { background-color:#bbb; color:#000; }\n    .user div.context ol li { color:#666; }\n    div.commands { margin-left: 40px; }\n    div.commands a { color:#555; text-decoration:none; }\n    .user div.commands a { color: black; }\n    #summary { background: #ffc; }\n    #summary h2 { font-weight: normal; color: #666; }\n    #explanation { background:#eee; }\n    #template, #template-not-exist { background:#f6f6f6; }\n    #template-not-exist ul { margin: 0 0 10px 20px; }\n    #template-not-exist .postmortem-section { margin-bottom: 3px; }\n    #unicode-hint { background:#eee; }\n    #traceback { background:#eee; }\n    #requestinfo { background:#f6f6f6; padding-left:120px; }\n    #summary table { border:none; background:transparent; }\n    #requestinfo h2, #requestinfo h3 { position:relative; margin-left:-100px; }\n    #requestinfo h3 { margin-bottom:-1em; }\n    .error { background: #ffc; }\n    .specific { color:#cc3300; font-weight:bold; }\n    h2 span.commands { font-size:.7em;}\n    span.commands a:link {color:#5E5694;}\n    pre.exception_value { font-family: sans-serif; color: #666; font-size: 1.5em; margin: 10px 0 10px 0; }\n    .append-bottom { margin-bottom: 10px; }\n  </style>\n  \n  <script type=\"text/javascript\">\n  //<!--\n    function getElementsByClassName(oElm, strTagName, strClassName){\n        // Written by Jonathan Snook, http://www.snook.ca/jon; Add-ons by Robert Nyman, http://www.robertnyman.com\n        var arrElements = (strTagName == \"*\" && document.all)? document.all :\n        oElm.getElementsByTagName(strTagName);\n        var arrReturnElements = new Array();\n        strClassName = strClassName.replace(/\\-/g, \"\\-\");\n        var oRegExp = new RegExp(\"(^|\\s)\" + strClassName + \"(\\s|$)\");\n        var oElement;\n        for(var i=0; i<arrElements.length; i++){\n            oElement = arrElements[i];\n            if(oRegExp.test(oElement.className)){\n                arrReturnElements.push(oElement);\n            }\n        }\n        return (arrReturnElements)\n    }\n    function hideAll(elems) {\n      for (var e = 0; e < elems.length; e++) {\n        elems[e].style.display = 'none';\n      }\n    }\n    window.onload = function() {\n      hideAll(getElementsByClassName(document, 'table', 'vars'));\n      hideAll(getElementsByClassName(document, 'ol', 'pre-context'));\n      hideAll(getElementsByClassName(document, 'ol', 'post-context'));\n      hideAll(getElementsByClassName(document, 'div', 'pastebin'));\n    }\n    function toggle() {\n      for (var i = 0; i < arguments.length; i++) {\n        var e = document.getElementById(arguments[i]);\n        if (e) {\n          e.style.display = e.style.display == 'none' ? 'block': 'none';\n        }\n      }\n      return false;\n    }\n    function varToggle(link, id) {\n      toggle('v' + id);\n      var s = link.getElementsByTagName('span')[0];\n      var uarr = String.fromCharCode(0x25b6);\n      var darr = String.fromCharCode(0x25bc);\n      s.innerHTML = s.innerHTML == uarr ? darr : uarr;\n      return false;\n    }\n    function switchPastebinFriendly(link) {\n      s1 = \"Switch to copy-and-paste view\";\n      s2 = \"Switch back to interactive view\";\n      link.innerHTML = link.innerHTML.trim() == s1 ? s2: s1;\n      toggle('browserTraceback', 'pastebinTraceback');\n      return false;\n    }\n    //-->\n  </script>\n  \n</head>\n<body>\n<div id=\"summary\">\n  <h1>OperationalError at /api/folder-local/</h1>\n  <pre class=\"exception_value\">no such column: videos_localscenefolders.date_added</pre>\n  <table class=\"meta\">\n\n    <tr>\n      <th>Request Method:</th>\n      <td>GET</td>\n    </tr>\n    <tr>\n      <th>Request URL:</th>\n      <td>http://127.0.0.1:8001/api/folder-local/</td>\n    </tr>\n\n    <tr>\n      <th>Django Version:</th>\n      <td>1.9.6</td>\n    </tr>\n\n    <tr>\n      <th>Exception Type:</th>\n      <td>OperationalError</td>\n    </tr>\n\n\n    <tr>\n      <th>Exception Value:</th>\n      <td><pre>no such column: videos_localscenefolders.date_added</pre></td>\n    </tr>\n\n\n    <tr>\n      <th>Exception Location:</th>\n      <td>c:\\pyvirtualenv\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py in execute, line 323</td>\n    </tr>\n\n    <tr>\n      <th>Python Executable:</th>\n      <td>c:\\pyvirtualenv\\Scripts\\python.exe</td>\n    </tr>\n    <tr>\n      <th>Python Version:</th>\n      <td>3.5.2</td>\n    </tr>\n    <tr>\n      <th>Python Path:</th>\n      <td><pre>[&#39;c:\\\\Yapo2\\\\YAPO&#39;,\n &#39;c:\\\\pyvirtualenv\\\\Scripts\\\\python35.zip&#39;,\n &#39;c:\\\\pyvirtualenv\\\\DLLs&#39;,\n &#39;c:\\\\pyvirtualenv\\\\lib&#39;,\n &#39;c:\\\\pyvirtualenv\\\\Scripts&#39;,\n &#39;c:\\\\yapo\\\\python\\\\Lib&#39;,\n &#39;c:\\\\yapo\\\\python\\\\DLLs&#39;,\n &#39;c:\\\\pyvirtualenv&#39;,\n &#39;c:\\\\pyvirtualenv\\\\lib\\\\site-packages&#39;,\n &#39;E:\\\\djangoProject\\\\YAPO\\\\YAPO&#39;]</pre></td>\n    </tr>\n    <tr>\n      <th>Server time:</th>\n      <td>Mon, 12 Sep 2016 18:10:15 +0200</td>\n    </tr>\n  </table>\n</div>\n\n\n\n\n<div id=\"traceback\">\n  <h2>Traceback <span class=\"commands\"><a href=\"#\" onclick=\"return switchPastebinFriendly(this);\">\n    Switch to copy-and-paste view</a></span>\n  </h2>\n  \n  <div id=\"browserTraceback\">\n    <ul class=\"traceback\">\n      \n        \n        <li class=\"frame django\">\n          <code>c:\\pyvirtualenv\\lib\\site-packages\\django\\db\\backends\\utils.py</code> in <code>execute</code>\n\n          \n            <div class=\"context\" id=\"c85214072\">\n              \n                <ol start=\"57\" class=\"pre-context\" id=\"pre85214072\">\n                \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre></pre></li>\n                \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>    def execute(self, sql, params=None):</pre></li>\n                \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>        self.db.validate_no_broken_transaction()</pre></li>\n                \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>        with self.db.wrap_database_errors:</pre></li>\n                \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>            if params is None:</pre></li>\n                \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>                return self.cursor.execute(sql)</pre></li>\n                \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>            else:</pre></li>\n                \n                </ol>\n              \n              <ol start=\"64\" class=\"context-line\">\n                <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>\n                return self.cursor.execute(sql, params)</pre> <span>...</span></li></ol>\n              \n                <ol start='65' class=\"post-context\" id=\"post85214072\">\n                  \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre></pre></li>\n                  \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>    def executemany(self, sql, param_list):</pre></li>\n                  \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>        self.db.validate_no_broken_transaction()</pre></li>\n                  \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>        with self.db.wrap_database_errors:</pre></li>\n                  \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"><pre>            return self.cursor.executemany(sql, param_list)</pre></li>\n                  \n                  <li onclick=\"toggle('pre85214072', 'post85214072')\"`
I can't add VLC path or video folders.
So is something wrong with my installation?

**Comment by sjclayton** [comment]
Did you run `makemigrations` and `migrate` before trying to start the server?

**Comment by sjclayton** [comment]
@curtwagner1984 ^^

**Comment by curtwagner1984** [comment]
@chengbert Is it possible you installed the experimental branch instead of the Master one ?

**Comment by sjclayton** [comment]
@chengbert If he followed the directions then it should have only pulled `master`

**Comment by curtwagner1984** [comment]
@sjclayton Maybe when you run `git pull` without specifying the branch it defaults to the most recently updated branch ?

**Comment by sjclayton** [comment]
@curtwagner1984 If he followed the directions then it should have only pulled master

**Comment by sjclayton** [comment]
@curtwagner1984 It shouldn't... I'll look into it

**Comment by sjclayton** [comment]
@curtwagner1984 in your settings for the repo -- go in and see which is selected as the "default branch"

**Comment by curtwagner1984** [comment]
@sjclayton It's set to Master ...

**Comment by sjclayton** [comment]
@curtwagner1984 Which it should be.... if he did have a problem and pulled the wrong one, then something you can try is switching the default branch from Master to AM... and then saving the change... then go right back in and change it back to Master again..

I will try cloning myself into a new dir and see what I get...

**Comment by sjclayton** [comment]
@curtwagner1984 I replied on #slack

**Comment by curtwagner1984** [comment]
@chengbert This is a django server message, It usually comes formated and specifies what the problem is... Here is an example:
![chrome_2016-09-12_23-04-18](https://cloud.githubusercontent.com/assets/20076369/18450914/9c766ffc-793d-11e6-9450-13d9a3e213b5.jpg)

It looks like you copy\pasted the html code of this error instead of the formatted error message. Anyhow it says:
><th>Exception Type:</th>\n <td>OperationalError</td>\n </tr>\n\n\n <tr>\n <th>Exception Value:</th>\n <td><pre>no such column: videos_localscenefolders.date_added</pre>

Which most likely means that you didn't do `makemigrations` and then `migrate`

**Comment by chengbert** [comment]
![yapo](https://cloud.githubusercontent.com/assets/22134897/18452528/7c11c222-793b-11e6-933e-0d7aa4078448.JPG)
This is the error I get when trying to add something.

I did do migrate. If I want to do makemigrations I get this:
![yapo2](https://cloud.githubusercontent.com/assets/22134897/18452581/bb7794be-793b-11e6-8510-791a2f9d2a88.JPG)

**Comment by curtwagner1984** [comment]
@chengbert Hey, look in the readme https://github.com/curtwagner1984/YAPO near the end, under update instructions.

**Comment by chengbert** [comment]
I already tried doing the update, still the same like in the last screenshot

**Comment by sjclayton** [comment]
@chengbert If you get that prompt... refer to the **NOTES** section at the end of the readme

and choose option 1 and enter `datetime.datetime.now()` and press enter
and if it prompts you to do it again, just keep doing that step over and over until it completes..

It may take a few times..

**Comment by chengbert** [comment]
Haha, wow that seems to work. I thought doing it once is enough.
Thanks, now I'll look into the programm.

**Comment by sjclayton** [comment]
@chengbert then anytime you want to pull the newest version you just do...

`git pull` from your C:\yapo\YAPO folder
and then run `makemigrations` and 'migrate` again before starting up the server, and you'll have the most current version of YAPO

:D
