### ISSUE TITLE
[Feature Request] Select how many items to be displayed per page

### ISSUE THREAD

**Issue by firewalkwithme93** [curtwagner1984/YAPO#6]
The ability to select how many items are displayed per page, e.g: 10, 30, 50, 80, 100 etc. when in grid view or regular view. This could potentially make mass tagging faster as you will not need to switch pages to select more items.

**Comment by curtwagner1984** [comment]
There now should be an option in the settings menu. It should persist even if you restart the server.

**Comment by curtwagner1984** [comment]
I'll assume that it works. If not we'll reopen this issue.
