### ISSUE TITLE
Multiple image upload buttons

### ISSUE THREAD

**Issue by firewalkwithme93** [curtwagner1984/YAPO#7]
This has already been acknowledged on the forum, but the nice blue Upload button is getting lonely when all the attention has to go to the small grey 'upload me' button when changing an Actor's image!

**Comment by sjclayton** [comment]
I may try to work on this today if I get time... see if I can't clean up the UI a bit

**Comment by curtwagner1984** [comment]
Ok, so I removed unnecessary buttons from the edit image interface. Now there are 4 buttons:
*  Upload: opens the upload file dialog
*  Edit: Lets you crop the current image
* OK: uploads the cropped image result
* Cancel: self explanatory.

There is still the issue of the ugly grey box. 
@sjclayton If you want to dig around there the it's under static/js/app/detail-profile-image.
The JS controllers are in static/js/app/controller.js and static/js/app/upload.js
This is by far the most problematic code in the whole project.

**Comment by sjclayton** [comment]
Something in the changes you made broke the cropping window, it doesn't display the image you select after you pick an image from Browse... therefore you can't effectively change images at all.

**Comment by curtwagner1984** [comment]
@sjclayton  Strange... It works on my end. Did you clear the cache before trying again ?

**Comment by sjclayton** [comment]
I will try again.... I didn't think something like that would be affected by caching though.

**Comment by sjclayton** [comment]
OK, I re-pulled it after resetting to the commit before you made the change, and I cleared my cache and you're right it does work (strange that something like that actually gets cached)... I wouldn't have thought that at all. Hence why I didn't try to clear it before. =P

**Comment by curtwagner1984** [comment]
So I guess we can consider this issue closed ?

**Comment by sjclayton** [comment]
Yeah I think it's safe to close it... as far as cleaning up and making the UI look better that can be dealt with seperately.
