### ISSUE TITLE
[Feature Request] Add FAVICON.ICO

### ISSUE THREAD

**Issue by sjclayton** [curtwagner1984/YAPO#9]
This needs to be done sometime, although not really a feature it would be nice to have because as of right now there isn't one. 

I may do it at some point...

**Comment by curtwagner1984** [comment]
It would require someone with an artistic talent... I'm not really such person.

**Comment by sjclayton** [comment]
I am pretty good with that kinda thing, that's why I mentioned that I might do it at some point soon when I have more time! =D

**Comment by sjclayton** [comment]
I have this done and ready to go... my only issue is in trying to get it to work on my local installation of YAPO.. I cannot figure out where to put it or how it should be called.

I'm not really familiar with AngularJS, but usually favicon.ico goes in the root folder for a website. However with the way YAPO is laid out I cannot figure out where this is... I tried a few different things and failed to get it to display on my end.

Something I noticed through my testing however, is even without the changes I've made to index.html or index-head.html in templates/videos/angular is that YAPO seems to not be looking for the favicon.ico anymore in the first place (I dunno if something was changed in one of the more recent commits that stopped it from searching for it, or where something else is happening). Before it used to attempt to look for it, and throw a 404 in the terminal output, it's stopped doing that now.

But like I said, at any rate the icon itself is ready.

**Comment by curtwagner1984** [comment]
This is a Django issue and not angular, after a bit of googling I learned that the favicon should go inside the root of the static folder.

And the markup in index-head.html should be:
`<link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>`

I've included this in the last commit with a placeholder icon I got from google, you just need to replace it in the root of 'static' folder. And adjust the extension in the markup if it's not png.

**Comment by sjclayton** [comment]
Alrighty, I wasn't 100% sure whether or not it was an Angular issue or Django... Just assumed it was an issue with Angular, because I figured Angular being the client that it had something to do with how it was calling the image to load it.. I did some reading / research and found lots of people complaining they were having a hard time with getting favicon's to load in their Angular projects.

I will upload the work-in-progress icon files, and adjust index-head.html shortly.

**Comment by curtwagner1984** [comment]
Maybe we will face angular problems as well with this issue. RIght now the problem was to get the server to serve the correct file.

**Comment by sjclayton** [comment]
It appeared to work fine with the placeholder image, so I think we're good. I just sent a pull request with the updated code and icon image files.

**Comment by curtwagner1984** [comment]
Seems to work fine! Good job!
